ALTER TABLE fonts ADD COLUMN family TEXT NOT NULL DEFAULT '';
ALTER TABLE fonts ADD COLUMN description TEXT NOT NULL DEFAULT '';
ALTER TABLE fonts ADD COLUMN authorName TEXT NOT NULL DEFAULT '';
ALTER TABLE fonts ADD COLUMN authorUrl TEXT NOT NULL DEFAULT '';
ALTER TABLE fonts ADD COLUMN uploaderIsAuthor INTEGER NOT NULL DEFAULT 0 CHECK(uploaderIsAuthor IN (0,1));

UPDATE fonts SET family=name WHERE family='';
